
export const initialCustomers = [
    {
        name: "David",
        company: "Mr. Jean",
        email: "inconnue@gmail.com",
        country: "Congo",
        notes: "",
        status: "lead",
    },
    {
        name: "Charles Guedj",
        company: "",
        email: "inconnue@gmail.com",
        phone: "+33777800015",
        country: "France",
        notes: "/",
        status: "lead",
    },
    {
        name: "Oumar",
        company: "",
        email: "inconnue@gmail.com",
        phone: "+2250770000000",
        country: "Cote d'ivoire",
        notes: "",
        status: "lead",
    },
    {
        name: "Elias Latrigue",
        company: "LTG Company LLC",
        email: "elias.latrigue@gmail.com",
        phone: "+33629253686",
        country: "USA",
        notes: "Manu's friend",
        status: "active",
    },
    {
        name: "Herve LEMEUNIER",
        company: "USN Spay",
        email: "surgeles@delicemer.fr",
        phone: "+33637148122",
        country: "Spay",
        notes: "President of USN Spay club",
        status: "active",
    },
    {
        name: "Stan",
        company: "RAGNARÖK ENERGY DRINK",
        email: "inconnue@gmail.com",
        phone: "+33625886912",
        country: "France",
        notes: "",
        status: "prospect",
    },
    {
        name: "Steph",
        company: "",
        email: "inconnue@gmail.com",
        phone: "",
        country: "France",
        notes: "",
        status: "lead",
    },
];
